name: Python package

on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENCE'
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
        os: [windows-latest,ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pytest
    - name: Coverage
      run: |
        coverage run --source=richkit -m unittest discover
    - name: Generate report through coverage
      run: |
        coverage report > coverage_report.txt
    - name: Upload code coverage as artifact
      uses: actions/upload-artifact@v1
      with:
        name: coverage_report.txt
        path: coverage_report.txt
    - name: Build documentation
      run: |
        pip install sphinx
        cd docs
        make html
